### ISSUE TITLE
您好，关于kindleear 漫画模块想请教一下

### ISSUE THREAD

**Issue by jinbasex** [insert0003/ComicDown#1]
由于有的漫画一卷超过50MB gmail 本身25MB 就很糟糕了，想请问一下您可以做一个单机版漫画模块吗？用于本地下载然后直接传入kindle。

**Comment by insert0003** [comment]
用comicdown 加kindlecomiccovert 可以很简单实现。你用的什么系统呢？
micnp <notifications@github.com> 于 2018年6月8日周五 上午11:14写道：

**Comment by jinbasex** [comment]
谢谢您的及时回复 这两天加班 忘记看了  我是一个代码小白 自然是使用windows 还多情不吝赐教

**Comment by insert0003** [comment]
我在linux下做的，稍微等等，我看看window下该怎么弄

**Comment by jinbasex** [comment]
多谢。

**Comment by insert0003** [comment]
你看看现在这个github里的ReadMe说明，能否看懂使用。

**Comment by jinbasex** [comment]
谢谢 我去看一下

**Comment by jinbasex** [comment]
环境变量 我带入了自己的C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\

但是这些在windows 上 我要怎么获取才好呢？
｛<pre>
pip install BeautifulSoup4
pip install lxml
</pre>

使用“kcc”进行漫画转换之前，需要安装以下的库。
<pre>
pip install psutil
pip install python-slugify
pip install Pillow
</pre>
｝

目前打开py文件是闪退 

还劳烦您有空的时候指点一下

**Comment by insert0003** [comment]
不好意思，没说明白。在window命令行下打开，不是直接双击。
把我的git代码下载到本地以后，按住Shift键右键点击空白处“在此处打开命令提示符",
在打开的窗口里，直接运行下面的命令就可以。
确保在Scripts的目录下有“pip.exe”这个文件。

pip install BeautifulSoup4
pip install lxml
pip install psutil
pip install python-slugify
pip install Pillow

**Comment by jinbasex** [comment]
多谢 我再试试 非常感谢

**Comment by jinbasex** [comment]
目前可以使用 getComic.py  直接打开getComic.py 可以下载文件 但是 下载的只有第一页
以及在 comic.txt 设置话数的时候 尝试设置海贼王830话 他就会自动下载830 到之前预设的 900多话
再次谢谢您的耐心，谢谢。

**Comment by insert0003** [comment]
>下载的只有第一页

我本地测试的时候只下载了一页，也一并上传了，现在改回去了。

**Comment by insert0003** [comment]
> 以及在 comic.txt 设置话数的时候 尝试设置海贼王830话 他就会自动下载830 到之前预设的 900多话

这个没有看懂，详细说一下啊？

**Comment by jinbasex** [comment]
原来如此 谢谢您   就是比如 原先  comic.txt  里面设置了 海贼王 903话 然后 我 设置了 93话  正常来水是直接下载93话 并结束 但是 我昨天执行之后 下载就会从93话 一直下载 一路下到弟903话

**Comment by insert0003** [comment]
哦哦，我是这么设计的，目的是一直下载。我加了个参数，这回试试呢。
url 起始话 结束话

**Comment by jinbasex** [comment]
好的 我再试试

**Comment by jinbasex** [comment]
非常感谢您 已经完美使用 谢谢。

**Comment by jinbasex** [comment]
很抱歉 再次打扰。最近测试的时候 出现
AttributeError: 'NoneType' object has no attribute 'findAll'

特再来请教您

完整代码如下


PS C:\Users\Administrator\Desktop\ComicDown-master> python getComic.py
downDir :  C:\Users\Administrator\Desktop\ComicDown-master/download
Getting 我的英雄學院 vol.180 from https://www.cartoonmad.com/comic/408501802016001.html.
Getting 我的英雄學院 vol.181 from https://www.cartoonmad.com/comic/408501812016001.html.
Getting 我的英雄學院 vol.182 from https://www.cartoonmad.com/comic/408501822016001.html.
Getting 我的英雄學院 vol.183 from https://www.cartoonmad.com/comic/408501832017001.html.
Getting 我的英雄學院 vol.184 from https://www.cartoonmad.com/comic/408501842017001.html.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "getComic.py", line 43, in run
    nav = soup.find("select").findAll("option")
AttributeError: 'NoneType' object has no attribute 'findAll'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "getComic.py", line 43, in run
    nav = soup.find("select").findAll("option")
AttributeError: 'NoneType' object has no attribute 'findAll'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "getComic.py", line 43, in run
    nav = soup.find("select").findAll("option")
AttributeError: 'NoneType' object has no attribute 'findAll'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "getComic.py", line 43, in run
    nav = soup.find("select").findAll("option")
AttributeError: 'NoneType' object has no attribute 'findAll'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "getComic.py", line 43, in run
    nav = soup.find("select").findAll("option")
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by jinbasex** [comment]
@insert0003

**Comment by jinbasex** [comment]
不好意思，再次打扰您，请问一下大佬还在吗？

**Comment by insert0003** [comment]
不好意思啊，哈哈，很久没看这个了，什么问题吗？

**Comment by jinbasex** [comment]
> 不好意思啊，哈哈，很久没看这个了，什么问题吗？

呜呜呜，大佬，您终于回复我了，详见上方2020年我发送的错误代码

**Comment by jinbasex** [comment]
Exception in thread Thread-5:
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "getComic.py", line 43, in run
nav = soup.find("select").findAll("option")
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by jinbasex** [comment]
现在跑都是出现这样的代码

**Comment by insert0003** [comment]
我研究研究啊

**Comment by jinbasex** [comment]
> 我研究研究啊

好的，有劳您了。

**Comment by insert0003** [comment]
cartoonmad貌似加了一些特殊的处理，目前我不知道怎么改。

**Comment by jinbasex** [comment]
> cartoonmad貌似加了一些特殊的处理，目前我不知道怎么改。

这样啊 
还是谢谢您，有劳您了，大佬。
再次感谢您为kindle漫画作出的贡献。
